blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostFeed

urlpatterns =[
    # Post views
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostFeed(), name='post_feed'),
]

minisite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},\
         name='django.contrib.sitemaps.views.sitemap'),

    #Maps the root URL and redirect to /catalog/
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True)),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# django-taggit
from taggit.managers import TaggableManager


# Custom model manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')

    # We specify the name of the reverse relationship, from User to Post,
    # with the related_name attribute
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    # auto_now_add  - The date will saved when creating an object
    created = models.DateTimeField(auto_now_add=True)

    # auto_now - the date will be updated automatically when creating an object
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()  # The default manager

    # Custom manager. i.e, we can retrieve all published post whose title
    # starts with 'who' using:
    # Post.published.filter(title__startswith='Who')
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        # Sort results by the publish field in descending order by default
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # It returns the canonical URL of the object
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    """
    Model representing a comment
    """

    # The related_name attribute allows us to name the attribute that we use
    # for the relation from the related object back to this one.
    # If the related_name is not defined, Django will use the undercase name
    # of the model followed by _set (that is, comment_set)
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from django.db.models import Count

from .models import Post, PublishedManager, Comment
from .forms import EmailPostForm, CommentForm

from taggit.models import Tag

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 post in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page,
                                                                           'posts': posts,
                                                                           'tag': tag})



# class PostListView(ListView):
#     """
#     Generic class-based view for a list of posts.
#     """
#     queryset = Post.published.all()

#     # It should be called post_list in the template, which is expected by ListView
#     context_object_name = 'posts'
#     #model = Post
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

#     #def get_queryset(self):
#         #return Post.objects.filter(status='published')




def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                                         status='published',
                                                         publish__year=year,
                                                         publish__month=month,
                                                         publish__day=day)

    # List of actives comments for this post.
    # We are building this QuerySet starting from the post object, using the
    # manager for related objects we defined as comments using the related_name
    # attribute of the relationship in the Comment model.
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create a comment object but don't save to the db yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        # There is no POST request, so the view is called by a GET request
        comment_form = CommentForm()

    # List of similar posts
    # We are passing it flat=True to get a flat list like [1, 2, 3, ...]
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id)\
                                                        .exclude(id=post.id)

    # We use the Count aggregation function to generate a calculated field
    # "same_tags" that contains the number of tags shared with all the
    # tags queried. Slice the result to retrieve only the first four posts.
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                                        .order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                                               'comments': comments,
                                                                               'comment_form': comment_form,
                                                                               'similar_posts': similar_posts})


def post_share(request, post_id):

    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            # Return True if all data submitted are valid

            # This attribute is a dictionary of form fields and their values.
            cd = form.cleaned_data

            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'],
                 cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,
                 post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@miniblog.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',
         {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>

        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                 <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                 </a>
                 {% if not foorlop.last  %}, {% endif %}
            {% endfor %}
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }} in {{ post.title }}
        </h2>
    {% endwith %}


    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
            <h2>Your comment has been added.</h2>
        {% else %}
            <h2>Add a new comment</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p><br>
            </form>
    {%  endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>

    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                 <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                 </a>
                 {% if not foorlop.last  %}, {% endif %}
            {% endfor %}
        </p>

        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        <!-- truncatewords_html truncates a string after a certain number of
                 words avoiding unclosed HTML tags -->
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    {% include "pagination.html" with page=posts %} <!-- use posts as object -->
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    Share a Post
{% endblock %}

{% block content %}

  {% if sent %}
    <h1>Email successfully sent</h1>
    <p>"{{ post.title }}" was successfully sent to {{ cd.to }}.</p>
   {% else %}
       <h1>Share: "{{ post.title }}" by email</h1>
       <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send E-mail">
       </form>
  {% endif %}
{% endblock %}